### ISSUE TITLE
AP CSA - Tri 2 - Assignment #0: FRQ #1

### ISSUE THREAD

**Issue by Dylanluo05** [Dylanluo05/spring_portfolio_dylan#1]
## VSCode Java Links: ##
[APCalender.java](https://github.com/Dylanluo05/spring_portfolio_dylan/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/APCalendar.java)
[CalendarApiController](https://github.com/Dylanluo05/spring_portfolio_dylan/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/CalendarApiController.java)
[Year.java](https://github.com/Dylanluo05/spring_portfolio_dylan/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calendar/Year.java)

## Debugging: ##
![image](https://user-images.githubusercontent.com/9831592/202756992-e980affe-9f20-40b0-8d3d-4d8cf1bb2e33.png)
![image](https://user-images.githubusercontent.com/9831592/202757147-69b77e98-e82a-4c8d-97a3-28898851d132.png)

## Postman: ##
isLeapYear:
![image](https://user-images.githubusercontent.com/9831592/202760224-71c43a26-6e07-48e5-9d31-31f0e0513fee.png)

firstDayOfYear:
![image](https://user-images.githubusercontent.com/9831592/202760303-a6af4faa-4001-44a5-ab7b-d1caff58c426.png)

numberOfLeapYears:
![image](https://user-images.githubusercontent.com/9831592/202760495-4ae7fb4d-74d7-4dac-a0e2-e692b757e9f2.png)

dayOfYear:
![image](https://user-images.githubusercontent.com/9831592/202760644-77705508-d885-47c5-a396-dce3a6bdbf96.png)

dayOfWeek:
![image](https://user-images.githubusercontent.com/9831592/202760731-179c2b0e-d6ae-4453-bab9-607935842aae.png)

**Comment by jm1021** [comment]
2.8
