### ISSUE TITLE
AP CSA - Tri 2 - FRQ 3 - Dylan Luo

### ISSUE THREAD

**Issue by Dylanluo05** [Dylanluo05/spring_portfolio_dylan#5]
### Checklist: ###
Hacks:
- [x] Finish rpnToResult for Calculator
- [x] Add unbalanced parenthesis check and in original FRQ, or other error checks. FYI, usually when structuring code with error checking it can greatly impact code structure.
- [x] Build in Power of operator ^:2 ^ 1 = 2, 2 ^ 2 = 4, 2 ^ 3 = 83. Build an API to receive an expression and respond with a result. This is a good opportunity to respond with an error if you built in parenthesis or other error checking.

Challenges:
- [x] Root function
- [x] ncr function that is useful in statistics

### Links: ###
[Code](https://github.com/Dylanluo05/spring_portfolio_dylan/tree/master/src/main/java/com/nighthawk/spring_portfolio/mvc/calculator)

### Postman: ###
![image](https://user-images.githubusercontent.com/9831592/205697435-dd843667-3703-4173-b929-9683da19f30e.png)
![image](https://user-images.githubusercontent.com/9831592/205697540-94ccecaf-01cc-47b4-9cbb-ef38f5af2993.png)
![image](https://user-images.githubusercontent.com/9831592/205697699-adcf6369-83d2-4977-a57f-934b44a07d6b.png)
![image](https://user-images.githubusercontent.com/9831592/205697996-fed9a4e7-4bea-4893-baef-30519d969f8d.png)
![image](https://user-images.githubusercontent.com/9831592/205698073-e7e3ebcc-5dbf-476a-aeff-8c92ace1fd8f.png)
![image](https://user-images.githubusercontent.com/9831592/205698148-a8747c58-3085-42c9-96f4-430b76058a15.png)
isBalanced returns false:
![image](https://user-images.githubusercontent.com/9831592/205698267-ba1336e0-e1ce-4e1f-b097-5a6dbb7ea505.png)

### Code Screenshots: ###
Tester function:
![image](https://user-images.githubusercontent.com/9831592/205693539-68731a84-a007-47f0-8632-d24cef0cbc0f.png)
isBalanced method:
![image](https://user-images.githubusercontent.com/9831592/205693587-86e592e5-e30e-459d-bb66-3c48e5d89e1c.png)
Checker for expression errors:
![image](https://user-images.githubusercontent.com/9831592/205696719-6da6fbc4-4bd5-4524-b9a2-e6c898839325.png)
Power, root, and ncr functions:
![image](https://user-images.githubusercontent.com/9831592/205693786-181b649a-7432-4990-b071-86b487c70940.png)
Tester function user interface output:
![image](https://user-images.githubusercontent.com/9831592/205696440-1c349899-77b5-47e3-b1c0-f6bfad39ab6e.png)

**Comment by dtsivkovski** [comment]
## Graded by Daniel Tsivkovski - 2.9/3

All requirements met including isBalanced function, shows additional work involving NCR function and ROOT function. Impressive use of the body request for the API Get method to make the power symbol compatible.
